wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561451.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561451.jgw
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561442.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561442.jgw
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561432.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561432.jgw
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561778.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561778.jgw
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561789.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561789.jgw
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/geo-24561800.jpg
wget https://geodesy.noaa.gov/storm_archive/storms/ernesto/JGW_MET/geo-24561800.jgw
